AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation base para el Punto 4 (Aprovisionamiento inicial de EC2 y S3)

Resources:
  #Creación de la Instancia EC2 básica
  MiServidorCloudFormation:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c7217cdde317cfec
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: Proyecto-Final-Servidor-Creado-Por-CloudFormation

  #Creación del Bucket S3
  MiBucketDeDatos:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-proyecto-final-mely-cloudformation

Outputs:
  IDDelServidorEC2:
    Description: Este es el ID de la máquina virtual que acabamos de crear
    Value: !Ref MiServidorCloudFormation

  NombreDelBucketS3:
    Description: Este es el nombre único de tu nuevo bucket de almacenamiento
    Value: !Ref MiBucketDeDatos
