name: Deploy Fintech App via AWS SSM

on:
  push:
    branches: [ main, develop ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias y Pytest
        run: |
          pip install pytest

      - name: Ejecutar Pruebas Automatizadas (QA)
        run: |
          pytest test/test_basico.py
      # ------------------------------

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Ejecutar comandos de despliegue vía SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-0c0cd6433017a8e78" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands": ["bash /home/ubuntu/environment/proyecto-st/scripts/deploy_ssm.sh"]}' \
            --region us-east-1
