name: Deploy Fintech App to EC2

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Desplegar en AWS EC2 vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |

            cd /home/ubuntu/environment/proyecto-st

            git pull origin develop

            if sudo docker compose up -d --build; then
              echo "Despliegue exitoso en S.T.F."
            else
              echo "Error detectado. Iniciando Rollback..."
              chmod +x scripts/rollback.sh
              ./scripts/rollback.sh
            fi
